"use client";

import React, { useState } from 'react';
import { pdf } from '@react-pdf/renderer';
import { SureReportTemplate, ReportData } from './SureReportTemplate';
import { Download, Loader2 } from 'lucide-react';
import { useLanguage } from '@/context/LanguageContext';

export default function RMAPdfGenerator({ 
  finalReport,
  buttonColor = "bg-green-500 hover:bg-green-400",
  redactOnTheFly = false,
  language = "en"
}: { 
  finalReport: ReportData;
  buttonText?: string;
  buttonColor?: string;
  redactOnTheFly?: boolean;
  language?: string;
}) {
  const [isGenerating, setIsGenerating] = useState(false);
  const { t } = useLanguage();

  const handleDownload = async () => {
    try {
      setIsGenerating(true);
      
      let reportToCompile = finalReport;
      if (redactOnTheFly) {
        const res = await fetch('/api/redact', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ reportJSON: finalReport })
        });
        if (!res.ok) throw new Error("Error redacting report");
        const data = await res.json();
        reportToCompile = data.redactedReport;
        
        reportToCompile.recommendations = (reportToCompile.recommendations || "") + "\n\n[CONFIDENTIALITY NOTE: This is a real audit report generated by the SURE platform. Corporate names, emails, physical addresses, phone numbers, and actual registration data have been redacted by AI to protect professional secrecy and client privacy].";
        reportToCompile.companyName = "[REDACTED INVESTIGATED ENTITY]";
        reportToCompile.taxId = "[REDACTED FOR SECURITY]";
        reportToCompile.website = "[REDACTED DOMAIN]";
      }

      const reportId = `SURE-RMA-${Date.now().toString().slice(-6)}`;
      const fileName = `SURE_RMA_${reportToCompile.companyName.replace(/\s+/g, '_')}.pdf`;
      
      const blob = await pdf(<SureReportTemplate data={reportToCompile} reportId={reportId} language={language} />).toBlob();
      const url = URL.createObjectURL(blob);
      
      const link = document.createElement('a');
      link.href = url;
      link.download = fileName;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      
      setTimeout(() => URL.revokeObjectURL(url), 1000);
    } catch (error) {
      console.error("Error generating PDF:", error);
      alert("Hubo un error al compilar el PDF. Por favor intenta de nuevo.");
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <button
      onClick={handleDownload}
      disabled={isGenerating}
      className={`w-full py-4 font-extrabold uppercase tracking-widest rounded-xl transition-all flex items-center justify-center gap-2 ${isGenerating ? 'bg-slate-700 text-slate-400 opacity-70 cursor-not-allowed' : `${buttonColor} text-black shadow-[0_0_20px_rgba(16,185,129,0.3)]`}`}
    >
      {isGenerating ? <><Loader2 className="w-5 h-5 animate-spin" /> {redactOnTheFly ? t('ui.btn_redacting') : t('ui.btn_compiling')}</> : <><Download className="w-5 h-5" /> {t('ui.btn_download_pdf')}</>}
    </button>
  );
}
